Lazy loading
YuliiaOsadchuk/task-manager-app pull request #9
Opened 2021-12-07 13:24 UTC by YuliiaOsadchuk

2021-12-07 16:48 UTC, b-sht-lionwood requested changes

2021-12-07 16:48 UTC, b-sht-lionwood commented on src/Router.tsx
> +const Signin = lazy(() => import('./components/signin/signin'));
fix pipeline errors

2021-12-07 16:48 UTC, b-sht-lionwood commented on src/Router.tsx
> +    <Suspense fallback={<div>Download...</div>}>
use material-ui loader here

2021-12-07 16:52 UTC, b-sht-lionwood requested changes

2021-12-07 16:52 UTC, b-sht-lionwood commented on src/Router.tsx
> +const Signin = lazy(() => import('./components/signin/signin'));
create new file `sign-in-lazy.tsx` in same folder where component, where you will export lazy loaded component

2021-12-07 16:52 UTC, b-sht-lionwood commented on src/Router.tsx
> +        <Route path={APP_ROUTES.SIGNIN} element={<Signin />} />
is is better to suspense each route separately.

You can create such high-ordero-component for that:
```
interface DtWithSuspenseProps {
  Component?: LazyExoticComponent<ComponentType>;
  loader?: ReactElement;
}

const DEFAULT_LOADER = <DtSkeleton variant='rectangular' />;

/**
 * This HOC intended to wrap components that you want to lazy load {@link https://reactjs.org/docs/code-splitting.html}
 *
 * @param {React.LazyExoticComponent<React.FC>} Component Component that you want to exclude from bundle and lazy load on demand
 * @param {React.ReactElement} loader Component that will be displayed till component load
 *
 * @example const componentToBeLazyLoaded = withSuspense(lazy(() => import(pathToComponent)));
 */
export const dtWithSuspense =
  (Component: LazyExoticComponent<FC>, loader: ReactElement | undefined = DEFAULT_LOADER): FC<DtWithSuspenseProps> =>
  (props): ReactElement => {
    return (
      <Suspense fallback={loader}>
        <Component {...props} />
      </Suspense>
    );
  };
```

2021-12-09 08:53 UTC, YuliiaOsadchuk commented
Download with slow 3g internet
<img width="607" alt="Screenshot 2021-12-09 at 10 52 54" src="https://user-images.githubusercontent.com/70544391/145364609-3a98b8b4-a91c-4601-abae-7e6b2b15821c.png">

2021-12-09 10:38 UTC, b-sht-lionwood requested changes

2021-12-09 10:38 UTC, b-sht-lionwood commented on src/Router.tsx
>  import React from 'react';
file name should be lowercase

2021-12-09 10:38 UTC, b-sht-lionwood commented on src/route-with-suspense.tsx
> +    );
add jsdoc documnetation here of how to use this component

2021-12-09 10:38 UTC, b-sht-lionwood commented on src/route-with-suspense.tsx
> +export const routeWithSuspense =
```suggestion
export const withSuspense =
```

2021-12-09 10:38 UTC, b-sht-lionwood commented on src/pages/home-page/home-page.tsx
> +const HomePage: React.FC = () => <Home />;
```suggestion
const HomePage = () => <Home />;
```

2021-12-09 10:38 UTC, b-sht-lionwood commented on src/components/signin/sign-in.tsx
> +const Signin: FC = () => {
```suggestion
const Signin = () => {
```

2021-12-09 10:38 UTC, b-sht-lionwood commented on src/components/home/home-lazy.ts
> +const HomeLazy: LazyExoticComponent<FC> = lazy(() => import('./home'));
No need to specify such file type
```suggestion
const HomeLazy = lazy(() => import('./home'));
```

2021-12-09 10:38 UTC, b-sht-lionwood commented on src/route-with-suspense.tsx
> +
add default loader

2021-12-09 10:38 UTC, b-sht-lionwood commented on src/components/signin/sign-in-lazy.tsx
> +const SigninLazy: LazyExoticComponent<FC> = lazy(() => import('./sign-in'));
No need to specify such file type
```suggestion
const SigninLazy = lazy(() => import('./sign-in'));
```

2021-12-09 15:00 UTC, b-sht-lionwood requested changes

2021-12-09 15:00 UTC, b-sht-lionwood commented on src/components/home/home-lazy.tsx
> +export default withSuspense(HomeLazy, <Progress />);
you already have same default loader inside function

2021-12-09 15:00 UTC, b-sht-lionwood commented on src/components/signin/sign-in-lazy.tsx
> +export default withSuspense(SigninLazy, <Progress />);
you already have same default loader inside function

2021-12-09 16:13 UTC, b-sht-lionwood approved these changes

2021-12-09 18:54 UTC, merged